# Generated by Django 5.1.3 on 2026-05-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subactivities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivity',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='status_subactivity',
            field=models.IntegerField(default=0),
        ),
    ]
