# sonar.organization y sonar.projectKey se pasan desde GitHub Actions.
sonar.sources=activities,subactivities,users,config_daily_work_hours
sonar.tests=activities,subactivities,users,config_daily_work_hours
sonar.test.inclusions=**/tests.py,**/tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
