# Generated by Django 5.1.3 on 2026-02-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type_activity',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Quiz', 'Quiz'), ('Taller', 'Taller'), ('Proyecto', 'Proyecto'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
